### ISSUE TITLE
상단 및 우측 메뉴의 링크가 잘못 걸려있음

### ISSUE THREAD

**Issue by reeny404** [R-KIMYONG/KUMAmovie#13]
. 이 빠져서 상대 경로가 아닌 절대 경로로 들어가 있음

/detail.html?id=278  -> ./detail.html?id=278

**Comment by eunohhh** [comment]
상단 및 우측 메뉴의 경로 수정했습니다.
login.html 은 아직 파일이 없어서 404 표시됩니다.

**Comment by reeny404** [comment]
감사합니다! 이슈 닫을께요!
